import Link from "next/link";
import Image from "next/image";
import { getLandingContent } from "@/lib/cms";
import { prisma } from "@/lib/prisma";
import { publicAnnouncementSelect, toAnnouncementCard } from "@/lib/announcements";
import { publicComplaintSelect, toPublicComplaint, PUBLIC_COMPLAINT_STATUSES } from "@/lib/complaint-projection";
import { AnnouncementCard } from "@/components/announcement-card";
import { StatusBadge } from "@/components/status-badge";
import { Icon } from "@/components/ui/icon";

export const dynamic = "force-dynamic";
function text(value: unknown) { return typeof value === "string" ? value : ""; }

export default async function Home() {
    const [content, announcements, complaintRows] = await Promise.all([
        getLandingContent(),
        prisma.announcement.findMany({ where: { status: "PUBLISHED" }, orderBy: [{ isPinned: "desc" }, { publishedAt: "desc" }, { createdAt: "desc" }], take: 3, select: publicAnnouncementSelect }),
        prisma.complaint.findMany({ where: { status: { in: [...PUBLIC_COMPLAINT_STATUSES] } }, orderBy: { updatedAt: "desc" }, take: 3, select: publicComplaintSelect }),
    ]);
    const hero = content.hero;
    const profile = content.profil;
    const contacts = [{ label: "Alamat", value: text(content.kontak.alamat) }, { label: "Telepon", value: text(content.kontak.telepon) }, { label: "WhatsApp", value: text(content.kontak.whatsapp) }, { label: "Email", value: text(content.kontak.email) }].filter((item) => item.value);
    const complaints = complaintRows.map(toPublicComplaint);
    const heroImage = text(hero.image) || "/images/panorama-pinaras.png";
    return <>
        <section className="relative isolate overflow-hidden bg-[var(--brand-deep)] text-white">
            <Image src={heroImage} alt="" fill priority sizes="100vw" className="object-cover object-center" />
            <div className="absolute inset-0 bg-gradient-to-r from-[#06354c]/95 via-[#06354c]/80 to-[#06354c]/35" />
            <div className="public-container relative grid gap-8 py-12 sm:py-16 lg:grid-cols-[1.7fr_1fr] lg:items-end lg:py-20">
                <div className="max-w-2xl"><p className="mb-4 text-sm font-semibold text-white/90">Sistem Informasi Peduli Pinaras</p><h1 className="text-3xl font-bold leading-tight sm:text-4xl lg:text-5xl">{text(hero.title)}</h1><p className="mt-5 max-w-xl text-lg leading-8 text-white/90">{text(hero.subtitle)}</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/warga/pengaduan/buat" className="ui-button bg-white text-[var(--brand-deep)] hover:bg-[var(--brand-soft)]">{text(hero.ctaText) || "Buat pengaduan"}<Icon name="arrow" /></Link><Link href="/pengaduan" className="ui-button border-white/50 bg-white/10 text-white hover:bg-white/20">{text(hero.ctaSecondaryText) || "Lihat forum pengaduan"}</Link></div></div>
                <div className="border-l-2 border-white/50 pl-5 lg:ml-8"><p className="text-lg font-semibold">Kelurahan Pinaras</p><p className="mt-2 text-sm leading-6 text-white/90">Informasi kelurahan dan layanan pengaduan dalam satu tempat.</p><Link href="/pengumuman" className="mt-4 inline-flex min-h-11 items-center gap-2 text-sm font-semibold text-white">Baca pengumuman <Icon name="arrow" /></Link></div>
            </div>
        </section>
        {content.statistics.length > 0 && <section className="border-b border-[var(--line)] bg-white"><div className="public-container grid grid-cols-2 gap-6 py-7 lg:grid-cols-4">{content.statistics.map((item) => <div key={item.id} className="min-w-0"><p className="text-2xl font-bold tabular-nums">{item.value} <span className="text-sm font-normal text-[var(--muted)]">{item.unit}</span></p><p className="mt-1 font-semibold">{item.label}</p><p className="mt-1 text-xs leading-5 text-[var(--muted)]">{item.source}{item.sourceYear ? " · data " + item.sourceYear : ""}{item.sourcePage ? " · hal. " + item.sourcePage : ""}</p></div>)}</div></section>}
        <section id="profil" className="public-container public-section grid gap-7 lg:grid-cols-[1fr_1.1fr]">
            <div><p className="public-kicker">Profil kelurahan</p><h2 className="public-title">Mengenal Pinaras</h2><p className="mt-4 leading-8 text-[var(--muted)]">{text(profile.shortDesc)}</p>{text(profile.longDesc) && <p className="mt-3 leading-8 text-[var(--muted)]">{text(profile.longDesc)}</p>}
                {[["Sejarah", profile.sejarah], ["Visi", profile.visi], ["Misi", profile.misi]].map(([label, value]) => text(value) ? <details key={text(label)} className="mt-3 border-b border-[var(--line)] py-3"><summary className="font-semibold">{text(label)}</summary><p className="mt-3 whitespace-pre-wrap leading-7 text-[var(--muted)]">{text(value)}</p></details> : null)}
            </div>
            <div className="rounded-xl border border-[var(--line)] bg-white p-5 sm:p-6"><p className="public-kicker">Layanan pengaduan</p><h3 className="text-2xl font-semibold">Sampaikan, pantau, dapatkan tanggapan</h3><ol className="mt-5 divide-y divide-[var(--line)]">{[{ title: "Masuk dengan Google", description: "Gunakan akun Google untuk mengakses ruang warga." }, { title: "Sampaikan pengaduan", description: "Tuliskan masalah, lokasi kejadian, dan lampirkan foto jika diperlukan." }, { title: "Pantau penanganannya", description: "Lihat status serta tanggapan admin melalui riwayat dan notifikasi." }].map((step, i) => <li key={step.title} className="flex gap-4 py-4"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-[var(--brand-soft)] font-semibold text-[var(--brand-dark)]">{i + 1}</span><div><h4 className="font-semibold">{step.title}</h4><p className="mt-1 text-sm leading-6 text-[var(--muted)]">{step.description}</p></div></li>)}</ol></div>
        </section>
        <section id="pengumuman" className="border-y border-[var(--line)] bg-white"><div className="public-container public-section"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="public-kicker">Informasi resmi</p><h2 className="public-title">Pengumuman terbaru</h2></div><Link href="/pengumuman" className="ui-button ui-button-secondary">Semua pengumuman <Icon name="arrow" /></Link></div>{announcements.length ? <div className="grid gap-4 md:grid-cols-3">{announcements.map((item) => <AnnouncementCard key={item.id} item={toAnnouncementCard(item)} compact />)}</div> : <div className="flex items-start gap-4 rounded-xl bg-[var(--surface)] p-5"><Icon name="announcement" className="size-8 text-[var(--brand)]" /><div><h3 className="font-semibold">Belum ada pengumuman terbit</h3><p className="mt-1 text-sm text-[var(--muted)]">Informasi kelurahan akan muncul di sini setelah diterbitkan oleh admin.</p></div></div>}</div></section>
        {(content.potentials.length > 0 || content.facilities.length > 0) && <section className="public-container public-section grid gap-8 lg:grid-cols-2">
            <div id="potensi"><p className="public-kicker">Potensi</p><h2 className="text-2xl font-semibold">Sumber daya kelurahan</h2><div className="mt-4 divide-y divide-[var(--line)]">{content.potentials.map((item) => <article key={item.id} className="py-4"><h3 className="font-semibold">{item.title}</h3><p className="mt-1 leading-7 text-[var(--muted)]">{item.description}</p>{item.sourceNote && <p className="mt-1 text-xs text-[var(--muted)]">{item.sourceNote}</p>}</article>)}</div></div>
            <div id="layanan"><p className="public-kicker">Fasilitas</p><h2 className="text-2xl font-semibold">Fasilitas dan layanan</h2><div className="mt-4 divide-y divide-[var(--line)]">{content.facilities.map((item) => <article key={item.id} className="py-4"><p className="text-xs text-[var(--brand-dark)]">{item.category}</p><h3 className="mt-1 font-semibold">{item.name}</h3><p className="mt-1 leading-7 text-[var(--muted)]">{item.description}</p>{item.sourceNote && <p className="mt-1 text-xs text-[var(--muted)]">{item.sourceNote}</p>}</article>)}</div></div>
        </section>}
        <section className="bg-white"><div className="public-container public-section"><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><p className="public-kicker">Transparansi pelayanan</p><h2 className="public-title">Forum pengaduan publik</h2><p className="mt-3 max-w-2xl text-[var(--muted)]">Pengaduan selesai dan ditolak ditampilkan tanpa identitas pelapor atau bukti privat.</p></div><Link href="/pengaduan" className="ui-button ui-button-secondary">Buka forum <Icon name="arrow" /></Link></div><div className="divide-y divide-[var(--line)]">{complaints.length ? complaints.map((item) => <Link key={item.ticketNumber} href={"/pengaduan/" + encodeURIComponent(item.ticketNumber)} className="flex flex-wrap items-center justify-between gap-4 py-5"><div className="min-w-0"><p className="text-xs text-[var(--muted)]">{item.ticketNumber} · {item.category}</p><h3 className="mt-1 font-semibold">{item.title}</h3></div><StatusBadge status={item.status} /></Link>) : <p className="rounded-xl bg-[var(--surface)] p-5 text-sm text-[var(--muted)]">Belum ada pengaduan yang tersedia untuk publik.</p>}</div></div></section>
        {content.gallery.length > 0 && <section id="galeri" className="public-container public-section"><p className="public-kicker">Galeri kelurahan</p><h2 className="public-title">Dokumentasi Pinaras</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{content.gallery.map((item) => <figure key={item.id} className="overflow-hidden rounded-xl border border-[var(--line)] bg-white"><Image unoptimized width={480} height={360} src={"/api/galeri/" + encodeURIComponent(item.id)} alt={item.caption || "Dokumentasi kelurahan"} loading="lazy" className="aspect-[4/3] w-full object-cover" /><figcaption className="p-3 text-sm">{item.caption}{item.credit && <span className="mt-1 block text-xs text-[var(--muted)]">Foto: {item.credit}</span>}</figcaption></figure>)}</div></section>}
        <section id="kontak" className="public-container public-section grid gap-6 lg:grid-cols-2"><div><p className="public-kicker">Lokasi dan kontak</p><h2 className="text-2xl font-semibold">Terhubung dengan kelurahan</h2>{text(content.lokasi.deskripsi) && <p className="mt-3 leading-7 text-[var(--muted)]">{text(content.lokasi.deskripsi)}</p>}{text(content.lokasi.alamat) && <p className="mt-3">{text(content.lokasi.alamat)}</p>}{text(content.lokasi.koordinat) && <p className="mt-2 text-sm text-[var(--muted)]">Koordinat: {text(content.lokasi.koordinat)}</p>}</div><div className="rounded-xl border border-[var(--line)] bg-white p-5">{contacts.length ? <dl className="grid gap-4">{contacts.map((item) => <div key={item.label}><dt className="text-sm text-[var(--muted)]">{item.label}</dt><dd className="mt-1 break-words font-semibold">{item.value}</dd></div>)}</dl> : <p className="text-[var(--muted)]">Kontak resmi kelurahan belum tersedia. Anda dapat menyampaikan pengaduan melalui ruang warga.</p>}<Link href="/warga/pengaduan/buat" className="ui-button ui-button-success mt-5">Sampaikan pengaduan <Icon name="arrow" /></Link></div></section>
    </>;
}
